server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://my-wookey-app-rds.c5ycesoyi03x.ap-northeast-2.rds.amazonaws.com:3306/boot_test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: "#an14921492#"
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 0.0.0.0 # docker redis
    port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false # osiv
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 20

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG
