server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false # osiv
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 20

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG
